apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - service-sftp.yaml
  - ingress.yaml
configMapGenerator:
  - name: vcf-services-caddy
    namespace: vcf-services
    files:
      - Caddyfile
generatorOptions:
  disableNameSuffixHash: true
